services:
    frontend:
        build:
            args:
                APP_PORT: ${APP_PORT}
                APP_NGINX_ROOT: ${APP_NGINX_ROOT}
        environment:
            APP_PORT: ${APP_PORT}
            APP_NGINX_ROOT: ${APP_NGINX_ROOT}
            NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
        ports:
            - ${APP_PORT}:${APP_PORT}
